replicaCount: 1
minReadySeconds: 15

image:
  repository: us-east1-docker.pkg.dev/central-binder-494822-a4/bites-apps/docs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

gateway:
  enabled: true
  name: bites-external
  sectionName: https
  hostnames:
    - docs.bites.com

healthCheckPolicy:
  enabled: true
  requestPath: /vision/camera-setup
  checkIntervalSec: 10
  timeoutSec: 5
  healthyThreshold: 1
  unhealthyThreshold: 3

probes:
  startup:
    periodSeconds: 5
    failureThreshold: 60
    timeoutSeconds: 5
  readiness:
    periodSeconds: 5
    failureThreshold: 3
    timeoutSeconds: 5
  liveness:
    periodSeconds: 15
    failureThreshold: 3
    timeoutSeconds: 5

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 2Gi

nodeSelector:
  cloud.google.com/gke-nodepool: apps-pool

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
