{{- if .Values.healthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "bites-docs.fullname" . }}-healthcheck
  labels:
    {{- include "bites-docs.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.healthCheckPolicy.checkIntervalSec }}
    timeoutSec: {{ .Values.healthCheckPolicy.timeoutSec }}
    healthyThreshold: {{ .Values.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.healthCheckPolicy.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: {{ .Values.healthCheckPolicy.requestPath }}
        portSpecification: USE_SERVING_PORT
  targetRef:
    group: ""
    kind: Service
    name: {{ include "bites-docs.fullname" . }}-service
{{- end }}
